version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    image: rockcoolsaint/node-docker
    # ports:
    #   - "3000-3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: